#include "SpellAdditionalProperties.hpp"

using namespace std;

const string SpellAdditionalProperties::PROPERTY_STATISTIC_MODIFIER_STR = "STATISTIC_MODIFIER_STR";
const string SpellAdditionalProperties::PROPERTY_STATISTIC_MODIFIER_DEX = "STATISTIC_MODIFIER_DEX";
const string SpellAdditionalProperties::PROPERTY_STATISTIC_MODIFIER_AGI = "STATISTIC_MODIFIER_AGI";
const string SpellAdditionalProperties::PROPERTY_STATISTIC_MODIFIER_HEA = "STATISTIC_MODIFIER_HEA";
const string SpellAdditionalProperties::PROPERTY_STATISTIC_MODIFIER_INT = "STATISTIC_MODIFIER_INT";
const string SpellAdditionalProperties::PROPERTY_STATISTIC_MODIFIER_WIL = "STATISTIC_MODIFIER_WIL";
const string SpellAdditionalProperties::PROPERTY_STATISTIC_MODIFIER_CHA = "STATISTIC_MODIFIER_CHA";
const string SpellAdditionalProperties::PROPERTY_STATISTIC_MODIFIER_EVADE = "STATISTIC_MODIFIER_EVADE";
const string SpellAdditionalProperties::PROPERTY_STATISTIC_MODIFIER_SOAK = "STATISTIC_MODIFIER_SOAK";

const string SpellAdditionalProperties::PROPERTY_RESISTANCE_MODIFIER_SLASH = "RESISTANCE_MODIFIER_SLASH";
const string SpellAdditionalProperties::PROPERTY_RESISTANCE_MODIFIER_PIERCE = "RESISTANCE_MODIFIER_PIERCE";
const string SpellAdditionalProperties::PROPERTY_RESISTANCE_MODIFIER_POUND = "RESISTANCE_MODIFIER_POUND";
const string SpellAdditionalProperties::PROPERTY_RESISTANCE_MODIFIER_HEAT = "RESISTANCE_MODIFIER_HEAT";
const string SpellAdditionalProperties::PROPERTY_RESISTANCE_MODIFIER_COLD = "RESISTANCE_MODIFIER_COLD";
const string SpellAdditionalProperties::PROPERTY_RESISTANCE_MODIFIER_ACID = "RESISTANCE_MODIFIER_ACID";
const string SpellAdditionalProperties::PROPERTY_RESISTANCE_MODIFIER_POISON = "RESISTANCE_MODIFIER_POISON";
const string SpellAdditionalProperties::PROPERTY_RESISTANCE_MODIFIER_HOLY = "RESISTANCE_MODIFIER_HOLY";
const string SpellAdditionalProperties::PROPERTY_RESISTANCE_MODIFIER_SHADOW = "RESISTANCE_MODIFIER_SHADOW";
const string SpellAdditionalProperties::PROPERTY_RESISTANCE_MODIFIER_ARCANE = "RESISTANCE_MODIFIER_ARCANE";
const string SpellAdditionalProperties::PROPERTY_RESISTANCE_MODIFIER_LIGHTNING = "RESISTANCE_MODIFIER_LIGHTNING";

const string SpellAdditionalProperties::PROPERTY_STATISTIC_MODIFIER_WEAR_OFF_SID = "SPELL_WEAR_OFF_SID";


