add_message_with_pause("MAISY_SPEECH_TEXT_SID")
add_message_with_pause("MAISY_SPEECH_TEXT2_SID")
add_message_with_pause("MAISY_SPEECH_TEXT3_SID")
add_message_with_pause("MAISY_SPEECH_TEXT4_SID")
add_message_with_pause("MAISY_SPEECH_TEXT5_SID")
add_message_with_pause("MAISY_SPEECH_TEXT6_SID")
add_message_with_pause("MAISY_SPEECH_TEXT7_SID")
add_message_with_pause("MAISY_SPEECH_TEXT8_SID")
add_message_with_pause("MAISY_SPEECH_TEXT9_SID")
add_message_with_pause("MAISY_SPEECH_TEXT10_SID")
add_message_with_pause("MAISY_SPEECH_TEXT11_SID")
add_message_with_pause("MAISY_SPEECH_TEXT12_SID")
clear_and_add_message("MAISY_SPEECH_TEXT13_SID")

