#include "CommandCustomValues.hpp"

using namespace std;

const string CommandCustomValues::COMMAND_CUSTOM_VALUES_ACTION_COST_VALUE = "COMMAND_CUSTOM_VALUES_ACTION_COST_VALUE"; 
const string CommandCustomValues::COMMAND_CUSTOM_VALUES_SELECTED_SPELL_ID = "COMMAND_CUSTOM_VALUES_SELECTED_SPELL_ID";
const string CommandCustomValues::COMMAND_CUSTOM_VALUES_DIRECTION = "COMMAND_CUSTOM_VALUES_DIRECTION";
const string CommandCustomValues::COMMAND_CUSTOM_VALUES_SKIP_TARGETTING = "COMMAND_CUSTOM_VALUES_SKIP_TARGETTING";

