require('constants')
require('fn')

-- get_treasure_items returns a CSV of items suitable for inclusion in
-- a treasure trove.
function get_treasure_items()
  local items = {MAGICI_SHARD_ID, GOLDEN_APPLE_ID, SILVER_APPLE_ID, SILVERWEED_ID, STONEFLOWER_ID, GAIN_ATTRIBUTES_POTION_ID, UNSTONING_POTION_ID, ANTIDOTE_POTION_ID, SPEED_POTION_ID, RAGE_POTION_ID, HEALING_POTION_ID, ETHER_POTION_ID, ENCHANTING_SCROLL_ID, IDENTIFY_SCROLL_ID, WARPING_SCROLL_ID, RING_FLAME_ID, RING_ICE_ID, RING_ACID_ID, RING_HOLINESS_ID, DRAGON_BREATH_WAND_ID, ARCANE_WAND_ID, FLAME_WAND_ID, LIGHTNING_WAND_ID, TELEPORT_WAND_ID, SHADOW_BOMB_ID, FIRE_BOMB_ID, LUMP_GOLD_ID, IVORY_TUSK_ID}

  return fn.array_to_csv(items)
end

