#pragma once

enum struct StatueType
{
  STATUE_TYPE_DECORATIVE = 0,
  STATUE_TYPE_REGULAR = 1
};

enum struct DecorativeStatueType
{
  DECORATIVE_STATUE_TYPE_FIRST = 0,
  DECORATIVE_STATUE_TYPE_KING = 0,
  DECORATIVE_STATUE_TYPE_QUEEN = 1,
  DECORATIVE_STATUE_TYPE_WARLORD = 2,
  DECORATIVE_STATUE_TYPE_KNIGHT = 3,
  DECORATIVE_STATUE_TYPE_HIGH_PRIEST = 4,
  DECORATIVE_STATUE_TYPE_SORCEROR = 5,
  DECORATIVE_STATUE_TYPE_LAST = 5
};

enum struct RegularStatueType
{
  REGULAR_STATUE_TYPE_PETRIFIED_CORPSE = 0,
  REGULAR_STATUE_TYPE_LAST = 1
};
