#pragma once
#include <string>

class TileCustomMapIDs
{
  public:
    static const std::string CUSTOM_MAP_ID_ISEN_DUN;
    static const std::string CUSTOM_MAP_ID_LAST_ISLAND_LAIR;
    static const std::string CUSTOM_MAP_ID_THE_BARROWS;
    static const std::string CUSTOM_MAP_ID_WINTERSEA_KEEP;
    static const std::string CUSTOM_MAP_ID_LAST_ROCK;

  protected:
    TileCustomMapIDs();
    ~TileCustomMapIDs();
};

enum TreeSpeciesID
{
  TREE_SPECIES_ASPEN,
  TREE_SPECIES_MAPLE,
  TREE_SPECIES_YEW,
  TREE_SPECIES_OAK,
  TREE_SPECIES_MOUNTAIN_ASH,
  TREE_SPECIES_ASH,
  TREE_SPECIES_BIRCH,
  TREE_SPECIES_CYPRESS,
  TREE_SPECIES_WALNUT,
  TREE_SPECIES_APPLE,
  TREE_SPECIES_CHERRY,
  TREE_SPECIES_PEACH,
  TREE_SPECIES_PLUM,
  TREE_SPECIES_PEAR,
  TREE_SPECIES_FIR,
  TREE_SPECIES_CEDAR,
  TREE_SPECIES_SPRUCE,
  TREE_SPECIES_PINE,
  TREE_SPECIES_WEED1,
  TREE_SPECIES_WEED2,
  TREE_SPECIES_WEED3,
  TREE_SPECIES_WEED4,
  TREE_SPECIES_WEED5,
  TREE_SPECIES_WEED6,
  TREE_SPECIES_WEED7,
  TREE_SPECIES_WEED8,
  TREE_SPECIES_WEED9,
  TREE_SPECIES_WEED10,
  TREE_SPECIES_WEED11,
  TREE_SPECIES_WEED12
};
