#pragma once

enum WorshipSiteType
{
  WORSHIP_SITE_CATHEDRAL = 0,
  WORSHIP_SITE_FORTIFIED_CHURCH = 1,
  WORSHIP_SITE_SIMPLE_CHURCH = 2,
  WORSHIP_SITE_GRAND_TEMPLE = 3,
  WORSHIP_SITE_SNAKING_TEMPLE = 4,
  WORSHIP_SITE_SIMPLE_TEMPLE = 5,
  WORSHIP_SITE_ISLAND_SACRIFICE_SITE = 6,
  WORSHIP_SITE_ROCKY_SACRIFICE_SITE = 7,
  WORSHIP_SITE_OVERGROWN_SACRIFICE_SITE = 8
};
