#include "FeatureDescriptionTextKeys.hpp"

using namespace std;

FeatureDescriptionTextKeys::FeatureDescriptionTextKeys()
{
}

const string FeatureDescriptionTextKeys::FEATURE_DESCRIPTION_DOOR               = "FEATURE_DESCRIPTION_DOOR";
const string FeatureDescriptionTextKeys::FEATURE_DESCRIPTION_GATE               = "FEATURE_DESCRIPTION_GATE";
const string FeatureDescriptionTextKeys::FEATURE_DESCRIPTION_EVIL_ALTAR         = "FEATURE_DESCRIPTION_EVIL_ALTAR";
const string FeatureDescriptionTextKeys::FEATURE_DESCRIPTION_GOOD_ALTAR         = "FEATURE_DESCRIPTION_GOOD_ALTAR";
const string FeatureDescriptionTextKeys::FEATURE_DESCRIPTION_NEUTRAL_ALTAR      = "FEATURE_DESCRIPTION_NEUTRAL_ALTAR";
const string FeatureDescriptionTextKeys::FEATURE_DESCRIPTION_FOUNTAIN           = "FEATURE_DESCRIPTION_FOUNTAIN";
const string FeatureDescriptionTextKeys::FEATURE_DESCRIPTION_FIRE_PILLAR        = "FEATURE_DESCRIPTION_FIRE_PILLAR";
const string FeatureDescriptionTextKeys::FEATURE_DESCRIPTION_PEW                = "FEATURE_DESCRIPTION_PEW";
const string FeatureDescriptionTextKeys::FEATURE_DESCRIPTION_KING_STATUE        = "FEATURE_DESCRIPTION_KING_STATUE";
const string FeatureDescriptionTextKeys::FEATURE_DESCRIPTION_QUEEN_STATUE       = "FEATURE_DESCRIPTION_QUEEN_STATUE";
const string FeatureDescriptionTextKeys::FEATURE_DESCRIPTION_WARLORD_STATUE     = "FEATURE_DESCRIPTION_WARLORD_STATUE";
const string FeatureDescriptionTextKeys::FEATURE_DESCRIPTION_KNIGHT_STATUE      = "FEATURE_DESCRIPTION_KNIGHT_STATUE";
const string FeatureDescriptionTextKeys::FEATURE_DESCRIPTION_HIGH_PRIEST_STATUE = "FEATURE_DESCRIPTION_HIGH_PRIEST_STATUE";
const string FeatureDescriptionTextKeys::FEATURE_DESCRIPTION_SORCEROR_STATUE    = "FEATURE_DESCRIPTION_SORCEROR_STATUE";
const string FeatureDescriptionTextKeys::FEATURE_DESCRIPTION_BENCH              = "FEATURE_DESCRIPTION_BENCH";
const string FeatureDescriptionTextKeys::FEATURE_DESCRIPTION_PETRIFIED_CORPSE_STATUE = "FEATURE_DESCRIPTION_PETRIFIED_CORPSE";
const string FeatureDescriptionTextKeys::FEATURE_DESCRIPTION_PETRIFIED_CORPSE_STATUE_WITH_DESC = "FEATURE_DESCRIPTION_PETRIFIED_CORPSE_STATUE_WITH_DESC";
const string FeatureDescriptionTextKeys::FEATURE_DESCRIPTION_SARCOPHAGUS        = "FEATURE_DESCRIPTION_SARCOPHAGUS";
const string FeatureDescriptionTextKeys::FEATURE_DESCRIPTION_SARCOPHAGUS_NO_INSCR = "FEATURE_DESCRIPTION_SARCOPHAGUS_NO_INSCR";
const string FeatureDescriptionTextKeys::FEATURE_DESCRIPTION_BARREL             = "FEATURE_DESCRIPTION_BARREL";
const string FeatureDescriptionTextKeys::FEATURE_DESCRIPTION_FORGE              = "FEATURE_DESCRIPTION_FORGE";
const string FeatureDescriptionTextKeys::FEATURE_DESCRIPTION_TANNERY            = "FEATURE_DESCRIPTION_TANNERY";
const string FeatureDescriptionTextKeys::FEATURE_DESCRIPTION_JEWELER_WORKBENCH  = "FEATURE_DESCRIPTION_JEWELER_WORKBENCH";
const string FeatureDescriptionTextKeys::FEATURE_DESCRIPTION_WHEEL_AND_LOOM     = "FEATURE_DESCRIPTION_WHEEL_AND_LOOM";
const string FeatureDescriptionTextKeys::FEATURE_DESCRIPTION_TRAP_GENERIC       = "FEATURE_DESCRIPTION_TRAP_GENERIC";
const string FeatureDescriptionTextKeys::FEATURE_DESCRIPTION_BED                = "FEATURE_DESCRIPTION_BED";
const string FeatureDescriptionTextKeys::FEATURE_DESCRIPTION_STONE_MARKER       = "FEATURE_DESCRIPTION_STONE_MARKER";
