#include "SkillTextKeys.hpp"

using namespace std;

SkillTextKeys::SkillTextKeys()
{
}

SkillTextKeys::~SkillTextKeys()
{
}

// SkillTextKeys
// General (NWP)
const string SkillTextKeys::SKILLS_GENERAL = "SKILLS_GENERAL";
const string SkillTextKeys::SKILL_GENERAL_ARCHERY = "SKILL_GENERAL_ARCHERY";
const string SkillTextKeys::SKILL_GENERAL_ARCHERY_INCREMENT = "SKILL_GENERAL_ARCHERY_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_AWARENESS = "SKILL_GENERAL_AWARENESS";
const string SkillTextKeys::SKILL_GENERAL_AWARENESS_INCREMENT = "SKILL_GENERAL_AWARENESS_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_BARGAINING = "SKILL_GENERAL_BARGAINING";
const string SkillTextKeys::SKILL_GENERAL_BARGAINING_INCREMENT = "SKILL_GENERAL_BARGAINING_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_BEASTMASTERY = "SKILL_GENERAL_BEASTMASTERY";
const string SkillTextKeys::SKILL_GENERAL_BEASTMASTERY_INCREMENT = "SKILL_GENERAL_BEASTMASTERY_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_BLIND_FIGHTING = "SKILL_GENERAL_BLIND_FIGHTING";
const string SkillTextKeys::SKILL_GENERAL_BLIND_FIGHTING_INCREMENT = "SKILL_GENERAL_BLIND_FIGHTING_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_BOATING = "SKILL_GENERAL_BOATING";
const string SkillTextKeys::SKILL_GENERAL_BOATING_INCREMENT = "SKILL_GENERAL_BOATING_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_BOWYER = "SKILL_GENERAL_BOWYER";
const string SkillTextKeys::SKILL_GENERAL_BOWYER_INCREMENT = "SKILL_GENERAL_BOWYER_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_BREWING = "SKILL_GENERAL_BREWING";
const string SkillTextKeys::SKILL_GENERAL_BREWING_INCREMENT = "SKILL_GENERAL_BREWING_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_CANTRIPS = "SKILL_GENERAL_CANTRIPS";
const string SkillTextKeys::SKILL_GENERAL_CANTRIPS_INCREMENT = "SKILL_GENERAL_CANTRIPS_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_CARRYING = "SKILL_GENERAL_CARRYING";
const string SkillTextKeys::SKILL_GENERAL_CARRYING_INCREMENT = "SKILL_GENERAL_CARRYING_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_COMBAT = "SKILL_GENERAL_COMBAT";
const string SkillTextKeys::SKILL_GENERAL_COMBAT_INCREMENT = "SKILL_GENERAL_COMBAT_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_CRAFTING = "SKILL_GENERAL_CRAFTING";
const string SkillTextKeys::SKILL_GENERAL_CRAFTING_INCREMENT = "SKILL_GENERAL_CRAFTING_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_DESERT_LORE = "SKILL_GENERAL_DESERT_LORE";
const string SkillTextKeys::SKILL_GENERAL_DESERT_LORE_INCREMENT = "SKILL_GENERAL_DESERT_LORE_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_DETECTION = "SKILL_GENERAL_DETECTION";
const string SkillTextKeys::SKILL_GENERAL_DETECTION_INCREMENT = "SKILL_GENERAL_DETECTION_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_DISARM_TRAPS = "SKILL_GENERAL_DISARM_TRAPS";
const string SkillTextKeys::SKILL_GENERAL_DISARM_TRAPS_INCREMENT = "SKILL_GENERAL_TRAPS_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_DUAL_WIELD = "SKILL_GENERAL_DUAL_WIELD";
const string SkillTextKeys::SKILL_GENERAL_DUAL_WIELD_INCREMENT = "SKILL_GENERAL_DUAL_WIELD_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_DUNGEONEERING = "SKILL_GENERAL_DUNGEONEERING";
const string SkillTextKeys::SKILL_GENERAL_DUNGEONEERING_INCREMENT = "SKILL_GENERAL_DUNGEONEERING_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_ESCAPE = "SKILL_GENERAL_ESCAPE";
const string SkillTextKeys::SKILL_GENERAL_ESCAPE_INCREMENT = "SKILL_GENERAL_ESCAPE_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_FORAGING = "SKILL_GENERAL_ESCAPE";
const string SkillTextKeys::SKILL_GENERAL_FORAGING_INCREMENT = "SKILL_GENERAL_FORAGING_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_FOREST_LORE = "SKILL_GENERAL_FOREST_LORE";
const string SkillTextKeys::SKILL_GENERAL_FOREST_LORE_INCREMENT = "SKILL_GENERAL_FOREST_LORE_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_FISHING = "SKILL_GENERAL_FISHING";
const string SkillTextKeys::SKILL_GENERAL_FISHING_INCREMENT = "SKILL_GENERAL_FISHING_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_FLETCHERY = "SKILL_GENERAL_FLETCHERY";
const string SkillTextKeys::SKILL_GENERAL_FLETCHERY_INCREMENT = "SKILL_GENERAL_FLETCHERY_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_HERBALISM = "SKILL_GENERAL_HERBALISM";
const string SkillTextKeys::SKILL_GENERAL_HERBALISM_INCREMENT = "SKILL_GENERAL_HERBALISM_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_HIDING = "SKILL_GENERAL_HIDING";
const string SkillTextKeys::SKILL_GENERAL_HIDING_INCREMENT = "SKILL_GENERAL_HIDING_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_HUNTING = "SKILL_GENERAL_HUNTING";
const string SkillTextKeys::SKILL_GENERAL_HUNTING_INCREMENT = "SKILL_GENERAL_HUNTING_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_INTIMIDATION = "SKILL_GENERAL_INTIMIDATION";
const string SkillTextKeys::SKILL_GENERAL_INTIMIDATION_INCREMENT = "SKILL_GENERAL_INTIMIDATION_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_JEWELER = "SKILL_GENERAL_JEWELER";
const string SkillTextKeys::SKILL_GENERAL_JEWELER_INCREMENT = "SKILL_GENERAL_JEWELER_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_JUMPING = "SKILL_GENERAL_JUMPING";
const string SkillTextKeys::SKILL_GENERAL_JUMPING_INCREMENT = "SKILL_GENERAL_JUMPING_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_LEADERSHIP = "SKILL_GENERAL_LEADERSHIP";
const string SkillTextKeys::SKILL_GENERAL_LEADERSHIP_INCREMENT = "SKILL_GENERAL_LEADERSHIP_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_LITERACY = "SKILL_GENERAL_LITERACY";
const string SkillTextKeys::SKILL_GENERAL_LITERACY_INCREMENT = "SKILL_GENERAL_LITERACY_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_LORE = "SKILL_GENERAL_LORE";
const string SkillTextKeys::SKILL_GENERAL_LORE_INCREMENT = "SKILL_GENERAL_LORE_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_MAGIC = "SKILL_GENERAL_MAGIC";
const string SkillTextKeys::SKILL_GENERAL_MAGIC_INCREMENT = "SKILL_GENERAL_MAGIC_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_MARSH_LORE = "SKILL_GENERAL_MARSH_LORE";
const string SkillTextKeys::SKILL_GENERAL_MARSH_LORE_INCREMENT = "SKILL_GENERAL_LORE_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_MEDICINE = "SKILL_GENERAL_MEDICINE";
const string SkillTextKeys::SKILL_GENERAL_MEDICINE_INCREMENT = "SKILL_GENERAL_MEDICINE_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_MOUNTAIN_LORE = "SKILL_GENERAL_MOUNTAIN_LORE";
const string SkillTextKeys::SKILL_GENERAL_MOUNTAIN_LORE_INCREMENT = "SKILL_GENERAL_MOUNTAIN_LORE_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_MOUNTAINEERING = "SKILL_GENERAL_MOUNTAINEERING";
const string SkillTextKeys::SKILL_GENERAL_MOUNTAINEERING_INCREMENT = "SKILL_GENERAL_MOUNTAINEERING_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_MUSIC = "SKILL_GENERAL_MUSIC";
const string SkillTextKeys::SKILL_GENERAL_MUSIC_INCREMENT = "SKILL_GENERAL_MUSIC_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_NIGHT_SIGHT = "SKILL_GENERAL_NIGHT_SIGHT";
const string SkillTextKeys::SKILL_GENERAL_NIGHT_SIGHT_INCREMENT = "SKILL_GENERAL_NIGHT_SIGHT_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_OCEANOGRAPHY = "SKILL_GENERAL_OCEANOGRAPHY";
const string SkillTextKeys::SKILL_GENERAL_OCEANOGRAPHY_INCREMENT = "SKILL_GENERAL_OCEANOGRAPHY_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_PAPERCRAFT = "SKILL_GENERAL_PAPERCRAFT";
const string SkillTextKeys::SKILL_GENERAL_PAPERCRAFT_INCREMENT = "SKILL_GENERAL_PAPERCRAFT_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_RELIGION = "SKILL_GENERAL_RELIGION";
const string SkillTextKeys::SKILL_GENERAL_RELIGION_INCREMENT = "SKILL_GENERAL_RELIGION_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_SCRIBING = "SKILL_GENERAL_SCRIBING";
const string SkillTextKeys::SKILL_GENERAL_SCRIBING_INCREMENT = "SKILL_GENERAL_SCRIBING_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_SKINNING = "SKILL_GENERAL_SKINNING";
const string SkillTextKeys::SKILL_GENERAL_SKINNING_INCREMENT = "SKILL_GENERAL_SKINNING_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_SMITHING = "SKILL_GENERAL_SMITHING";
const string SkillTextKeys::SKILL_GENERAL_SMITHING_INCREMENT = "SKILL_GENERAL_SMITHING_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_SPELUNKING = "SKILL_GENERAL_SPELUNKING";
const string SkillTextKeys::SKILL_GENERAL_SPELUNKING_INCREMENT = "SKILL_GENERAL_SPELUNKING_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_STEALTH = "SKILL_GENERAL_STEALTH";
const string SkillTextKeys::SKILL_GENERAL_STEALTH_INCREMENT = "SKILL_GENERAL_STEALTH_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_SWIMMING = "SKILL_GENERAL_SWIMMING";
const string SkillTextKeys::SKILL_GENERAL_SWIMMING_INCREMENT = "SKILL_GENERAL_SWIMMING_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_TANNING = "SKILL_GENERAL_TANNING";
const string SkillTextKeys::SKILL_GENERAL_TANNING_INCREMENT = "SKILL_GENERAL_TANNING_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_THIEVERY = "SKILL_GENERAL_THIEVERY";
const string SkillTextKeys::SKILL_GENERAL_THIEVERY_INCREMENT = "SKILL_GENERAL_THIEVERY_INCREMENT";
const string SkillTextKeys::SKILL_GENERAL_WEAVING = "SKILL_GENERAL_WEAVING";
const string SkillTextKeys::SKILL_GENERAL_WEAVING_INCREMENT = "SKILL_GENERAL_WEAVING_INCREMENT";

// Weapon (Melee)
const string SkillTextKeys::SKILLS_WEAPON = "SKILLS_WEAPON";
const string SkillTextKeys::SKILL_MELEE_AXES = "SKILL_MELEE_AXES";
const string SkillTextKeys::SKILL_MELEE_AXES_INCREMENT = "SKILL_MELEE_AXES_INCREMENT";
const string SkillTextKeys::SKILL_MELEE_SHORT_BLADES = "SKILL_MELEE_SHORT_BLADES";
const string SkillTextKeys::SKILL_MELEE_SHORT_BLADES_INCREMENT = "SKILL_MELEE_SHORT_BLADES_INCREMENT";
const string SkillTextKeys::SKILL_MELEE_LONG_BLADES = "SKILL_MELEE_LONG_BLADES";
const string SkillTextKeys::SKILL_MELEE_LONG_BLADES_INCREMENT = "SKILL_MELEE_LONG_BLADES_INCREMENT";
const string SkillTextKeys::SKILL_MELEE_BLUDGEONS = "SKILL_MELEE_BLUDGEONS";
const string SkillTextKeys::SKILL_MELEE_BLUDGEONS_INCREMENT = "SKILL_MELEE_BLUDGEONS_INCREMENT";
const string SkillTextKeys::SKILL_MELEE_DAGGERS = "SKILL_MELEE_DAGGERS";
const string SkillTextKeys::SKILL_MELEE_DAGGERS_INCREMENT = "SKILL_MELEE_DAGGERS_INCREMENT";
const string SkillTextKeys::SKILL_MELEE_RODS_AND_STAVES = "SKILL_MELEE_RODS_AND_STAVES";
const string SkillTextKeys::SKILL_MELEE_RODS_AND_STAVES_INCREMENT = "SKILL_MELEE_RODS_AND_STAVES_INCREMENT";
const string SkillTextKeys::SKILL_MELEE_SPEARS = "SKILL_MELEE_SPEARS";
const string SkillTextKeys::SKILL_MELEE_SPEARS_INCREMENT = "SKILL_MELEE_SPEARS_INCREMENT";
const string SkillTextKeys::SKILL_MELEE_UNARMED = "SKILL_MELEE_UNARMED";
const string SkillTextKeys::SKILL_MELEE_UNARMED_INCREMENT = "SKILL_MELEE_UNARMED_INCREMENT";
const string SkillTextKeys::SKILL_MELEE_WHIPS = "SKILL_MELEE_WHIPS";
const string SkillTextKeys::SKILL_MELEE_WHIPS_INCREMENT = "SKILL_MELEE_WHIPS_INCREMENT";
const string SkillTextKeys::SKILL_MELEE_EXOTIC = "SKILL_MELEE_EXOTIC";
const string SkillTextKeys::SKILL_MELEE_EXOTIC_INCREMENT = "SKILL_MELEE_EXOTIC_INCREMENT";

// Weapon (Ranged)
const string SkillTextKeys::SKILLS_RANGED_WEAPON = "SKILLS_RANGED_WEAPON";
const string SkillTextKeys::SKILL_RANGED_AXES = "SKILL_RANGED_AXES";
const string SkillTextKeys::SKILL_RANGED_AXES_INCREMENT = "SKILL_RANGED_AXES_INCREMENT";
const string SkillTextKeys::SKILL_RANGED_BLADES = "SKILL_RANGED_BLADES";
const string SkillTextKeys::SKILL_RANGED_BLADES_INCREMENT = "SKILL_RANGED_BLADES_INCREMENT";
const string SkillTextKeys::SKILL_RANGED_BLUDGEONS = "SKILL_RANGED_BLUDGEONS";
const string SkillTextKeys::SKILL_RANGED_BLUDGEONS_INCREMENT = "SKILL_RANGED_BLUDGEONS_INCREMENT";
const string SkillTextKeys::SKILL_RANGED_BOWS = "SKILL_RANGED_BOWS";
const string SkillTextKeys::SKILL_RANGED_BOWS_INCREMENT = "SKILL_RANGED_BOWS_INCREMENT";
const string SkillTextKeys::SKILL_RANGED_CROSSBOWS = "SKILL_RANGED_CROSSBOWS";
const string SkillTextKeys::SKILL_RANGED_CROSSBOWS_INCREMENT = "SKILL_RANGED_CROSSBOWS_INCREMENT";
const string SkillTextKeys::SKILL_RANGED_DAGGERS = "SKILL_RANGED_DAGGERS";
const string SkillTextKeys::SKILL_RANGED_DAGGERS_INCREMENT = "SKILL_RANGED_DAGGERS_INCREMENT";
const string SkillTextKeys::SKILL_RANGED_ROCKS = "SKILL_RANGED_ROCKS";
const string SkillTextKeys::SKILL_RANGED_ROCKS_INCREMENT = "SKILL_RANGED_ROCKS_INCREMENT";
const string SkillTextKeys::SKILL_RANGED_SLINGS = "SKILL_RANGED_SLINGS";
const string SkillTextKeys::SKILL_RANGED_SLINGS_INCREMENT = "SKILL_RANGED_SLINGS_INCREMENT";
const string SkillTextKeys::SKILL_RANGED_SPEARS = "SKILL_RANGED_SPEARS";
const string SkillTextKeys::SKILL_RANGED_SPEARS_INCREMENT = "SKILL_RANGED_SPEARS_INCREMENT";
const string SkillTextKeys::SKILL_RANGED_EXOTIC = "SKILL_RANGED_EXOTIC";
const string SkillTextKeys::SKILL_RANGED_EXOTIC_INCREMENT = "SKILL_RANGED_EXOTIC_INCREMENT";

// Magic
const string SkillTextKeys::SKILLS_MAGIC = "SKILLS_MAGIC";
const string SkillTextKeys::SKILL_MAGIC_ARCANE = "SKILL_MAGIC_ARCANE";
const string SkillTextKeys::SKILL_MAGIC_ARCANE_INCREMENT = "SKILL_MAGIC_ARCANE_INCREMENT";
const string SkillTextKeys::SKILL_MAGIC_DIVINE = "SKILL_MAGIC_DIVINE";
const string SkillTextKeys::SKILL_MAGIC_DIVINE_INCREMENT = "SKILL_MAGIC_DIVINE_INCREMENT";
const string SkillTextKeys::SKILL_MAGIC_MYSTIC = "SKILL_MAGIC_MYSTIC";
const string SkillTextKeys::SKILL_MAGIC_MYSTIC_INCREMENT = "SKILL_MAGIC_MYSTIC_INCREMENT";
const string SkillTextKeys::SKILL_MAGIC_PRIMORDIAL = "SKILL_MAGIC_PRIMORDIAL";
const string SkillTextKeys::SKILL_MAGIC_PRIMORDIAL_INCREMENT = "SKILL_MAGIC_PRIMORDIAL_INCREMENT";

// Skill usage
const string SkillTextKeys::SKILL_USAGE_WEAPON = "SKILL_USAGE_WEAPON";
const string SkillTextKeys::SKILL_USAGE_MAGIC = "SKILL_USAGE_MAGIC";
const string SkillTextKeys::SKILL_USAGE_UNIMPLEMENTED = "SKILL_USAGE_UNIMPLEMENTED";