#include "SpellcastingTextKeys.hpp"

using namespace std;

SpellcastingTextKeys::SpellcastingTextKeys()
{
}

const string SpellcastingTextKeys::SPELLCASTING_NO_MAGICAL_KNOWLEDGE = "SPELLCASTING_NO_MAGICAL_KNOWLEDGE";
const string SpellcastingTextKeys::SPELLCASTING_UNAVAILABLE_ON_WORLD_MAP = "SPELLCASTING_UNAVAILABLE_ON_WORLD_MAP";
const string SpellcastingTextKeys::SPELLCASTING_SCREEN_PROMPT = "SPELLCASTING_SCREEN_PROMPT";
const string SpellcastingTextKeys::SPELLCASTING_INSUFFICIENT_POWER = "SPELLCASTING_INSUFFICIENT_POWER";
const string SpellcastingTextKeys::SPELLCASTING_BONUS_INCREASED = "SPELLCASTING_BONUS_INCREASED";
const string SpellcastingTextKeys::SPELLCASTING_NO_MAGIC_SKILL = "SPELLCASTING_NO_MAGIC_SKILL";

const string SpellcastingTextKeys::SPELLCASTING_TARGET_SELF_ABRV = "SPELLCASTING_TARGET_SELF_ABRV";
const string SpellcastingTextKeys::SPELLCASTING_BEAM_ABRV = "SPELLCASTING_BEAM_ABRV";
const string SpellcastingTextKeys::SPELLCASTING_REFLECTIVE_BEAM_ABRV = "SPELLCASTING_REFLECTIVE_BEAM_ABRV";
const string SpellcastingTextKeys::SPELLCASTING_CONE_ABRV = "SPELLCASTING_CONE_ABRV";
const string SpellcastingTextKeys::SPELLCASTING_BALL_ABRV = "SPELLCASTING_BALL_ABRV";
