#include "SpellFailureTextKeys.hpp"

using namespace std;

const string SpellFailureTextKeys::SPELL_FAILURE_DAMAGE_MARGINAL = "SPELL_FAILURE_DAMAGE_MARGINAL";
const string SpellFailureTextKeys::SPELL_FAILURE_DAMAGE_LESSER = "SPELL_FAILURE_DAMAGE_LESSER";
const string SpellFailureTextKeys::SPELL_FAILURE_DAMAGE_SEVERE = "SPELL_FAILURE_DAMAGE_SEVERE";

const string SpellFailureTextKeys::SPELL_FAILURE_SUMMONED_CREATURES_MARGINAL = "SPELL_FAILURE_SUMMONED_CREATURES_MARGINAL";
const string SpellFailureTextKeys::SPELL_FAILURE_SUMMONED_CREATURES_LESSER = "SPELL_FAILURE_SUMMONED_CREATURES_LESSER";
const string SpellFailureTextKeys::SPELL_FAILURE_SUMMONED_CREATURES_SEVERE = "SPELL_FAILURE_SUMMONED_CREATURES_SEVERE";

