#pragma once

enum struct EffectType
{
  EFFECT_TYPE_NULL = 0,
  EFFECT_TYPE_HEALING = 1,
  EFFECT_TYPE_IDENTIFY = 2,
  EFFECT_TYPE_ETHER = 3,
  EFFECT_TYPE_FRUIT_JUICE = 4,
  EFFECT_TYPE_TELEPORT = 5,
  EFFECT_TYPE_ANTIDOTE = 6,
  EFFECT_TYPE_AMUT = 7,
  EFFECT_TYPE_SPEED = 8,
  EFFECT_TYPE_UNSTONING = 9,
  EFFECT_TYPE_UNBINDING = 10,
  EFFECT_TYPE_RESTORE_STATISTICS = 11,
  EFFECT_TYPE_UNBLINDING = 12,
  EFFECT_TYPE_RECHARGING = 13,
  EFFECT_TYPE_INCORPOREAL = 14,
  EFFECT_TYPE_ENCHANTING = 15,
  EFFECT_TYPE_FLYING = 16,
  EFFECT_TYPE_GAIN_ATTRIBUTES = 17,
  EFFECT_TYPE_MODIFY_STATISTICS = 18,
  EFFECT_TYPE_TIMEWALK = 19,
  EFFECT_TYPE_LAST = 20
};
