#pragma once

enum EffectType
{
  EFFECT_TYPE_NULL = 0,
  EFFECT_TYPE_HEALING = 1,
  EFFECT_TYPE_IDENTIFY = 2,
  EFFECT_TYPE_ETHER = 3,
  EFFECT_TYPE_FRUIT_JUICE = 4,
  EFFECT_TYPE_TELEPORT = 5,
  EFFECT_TYPE_LAST = 6
};
