#pragma once

enum SpellShapeType
{
  SPELL_SHAPE_TARGET_SELF = 0,
  SPELL_SHAPE_BEAM = 1,
  SPELL_SHAPE_REFLECTIVE_BEAM = 2,
  SPELL_SHAPE_CONE = 3,
  SPELL_SHAPE_BALL = 4,
  SPELL_SHAPE_CROSS = 5,
  SPELL_SHAPE_LAST = 6
};

