#pragma once

enum struct SpellShapeType
{
  SPELL_SHAPE_TARGET_SELF = 0,
  SPELL_SHAPE_BEAM = 1,
  SPELL_SHAPE_REFLECTIVE_BEAM = 2,
  SPELL_SHAPE_CONE = 3,
  SPELL_SHAPE_BALL = 4,
  SPELL_SHAPE_CROSS = 5,
  SPELL_SHAPE_STORM = 6,
  SPELL_SHAPE_LAST = 7
};

enum struct MagicClassification
{
  MAGIC_CLASSIFICATION_UNDEFINED = -1,
  MAGIC_CLASSIFICATION_ATTACK = 0,
  MAGIC_CLASSIFICATION_HEALING = 1,
  MAGIC_CLASSIFICATION_BUFF = 2,
  MAGIC_CLASSIFICATION_UTILITY = 3
};


