#include "CreatureProperties.hpp"

using namespace std;

CreatureProperties::CreatureProperties()
{
}

CreatureProperties::~CreatureProperties()
{
}

const string CreatureProperties::CREATURE_PROPERTIES_SPEECH_TEXT_SID = "CREATURE_PROPERTIES_SPEECH_TEXT_SID";
const string CreatureProperties::CREATURE_PROPERTIES_LAST_BESTIARY_SEARCH = "CREATURE_PROPERTIES_LAST_BESTIARY_SEARCH";
const string CreatureProperties::CREATURE_PROPERTIES_HASTE_MODIFIER = "CREATURE_PROPERTIES_HASTE_MODIFIER";
const string CreatureProperties::CREATURE_PROPERTIES_FOLLOWS_CR_ID  = "CREATURE_PROPERTIES_FOLLOWS_CR_ID";
const string CreatureProperties::CREATURE_PROPERTIES_AUTOMOVEMENT_AVAILABLE_DIRECTIONS = "CREATURE_PROPERTIES_AUTOMOVEMENT_AVAILABLE_DIRECTIONS";
const string CreatureProperties::CREATURE_PROPERTIES_AUTOMOVEMENT_COORDS_VISITED = "CREATURE_PROPERTIES_AUTOMOVEMENT_COORDS_VISITED";


