#include "CreatureProperties.hpp"

using namespace std;

CreatureProperties::CreatureProperties()
{
}

CreatureProperties::~CreatureProperties()
{
}

const string CreatureProperties::CREATURE_PROPERTIES_SPEECH_TEXT_SID = "CREATURE_PROPERTIES_SPEECH_TEXT_SID";
const string CreatureProperties::CREATURE_PROPERTIES_LAST_BESTIARY_SEARCH = "CREATURE_PROPERTIES_LAST_BESTIARY_SEARCH";
const string CreatureProperties::CREATURE_PROPERTIES_LAST_ITEM_CODEX_SEARCH = "CREATURE_PROPERTIES_LAST_ITEM_CODEX_SEARCH";
const string CreatureProperties::CREATURE_PROPERTIES_FOLLOWS_CR_ID  = "CREATURE_PROPERTIES_FOLLOWS_CR_ID";
const string CreatureProperties::CREATURE_PROPERTIES_AUTOMOVEMENT_COORDS_VISITED = "CREATURE_PROPERTIES_AUTOMOVEMENT_COORDS_VISITED";
const string CreatureProperties::CREATURE_PROPERTIES_LEAVES_CORPSE = "CREATURE_PROPERTIES_LEAVES_CORPSE";
const string CreatureProperties::CREATURE_PROPERTIES_LEAVES_EQUIPMENT = "CREATURE_PROPERTIES_LEAVES_EQUIPMENT";
const string CreatureProperties::CREATURE_PROPERTIES_ALLOWS_RANDOM_DROPS = "CREATURE_PROPERTIES_ALLOWS_RANDOM_DROPS";
const string CreatureProperties::CREATURE_PROPERTIES_STOLEN_FROM = "CREATURE_PROPERTIES_STOLEN_FROM";
const string CreatureProperties::CREATURE_PROPERTIES_PACIFIED = "CREATURE_PROPERTIES_PACIFIED";
const string CreatureProperties::CREATURE_PROPERTIES_WINNER = "CREATURE_PROPERTIES_WINNER";
const string CreatureProperties::CREATURE_PROPERTIES_IGNORE_RACIAL_MOVEMENT_RESTRICTIONS = "CREATURE_PROPERTIES_IGNORE_RACIAL_MOVEMENT_RESTRICTIONS";
const string CreatureProperties::CREATURE_PROPERTIES_BACKSTABBED = "CREATURE_PROPERTIES_BACKSTABBED";
const string CreatureProperties::CREATURE_PROPERTIES_TELEPORTED = "CREATURE_PROPERTIES_TELEPORTED";
const string CreatureProperties::CREATURE_PROPERTIES_FREE_HIDDEN_ACTIONS = "CREATURE_PROPERTIES_FREE_HIDDEN_ACTIONS";
const string CreatureProperties::CREATURE_PROPERTIES_FIRST_KILL_ID = "CREATURE_PROPERTIES_FIRST_KILL_ID";
const string CreatureProperties::CREATURE_PROPERTIES_NO_EXP = "CREATURE_PROPERTIES_NO_EXP";
const string CreatureProperties::CREATURE_PROPERTIES_TAMED = "CREATURE_PROPERTIES_TAMED";
const string CreatureProperties::CREATURE_PROPERTIES_LEADER_ID = "CREATURE_PROPERTIES_LEADER_ID";
const string CreatureProperties::CREATURE_PROPERTIES_FOLLOWER_PREFIX = "CREATURE_PROPERTIES_FOLLOWER_";
const string CreatureProperties::CREATURE_PROPERTIES_HIRELING_CHAT_SID = "CREATURE_PROPERTIES_HIRELING_CHAT_SID";
const string CreatureProperties::CREATURE_PROPERTIES_HIRE_FEE = "CREATURE_PROPERTIES_HIRE_FEE";
const string CreatureProperties::CREATURE_PROPERTIES_HIRELINGS_HIRED = "CREATURE_PROPERTIES_HIRELINGS_HIRED";
const string CreatureProperties::CREATURE_PROPERTIES_ADVENTURERS_JOINED = "CREATURE_PROPERTIES_ADVENTURERS_JOINED";
const string CreatureProperties::CREATURE_PROPERTIES_PRIMARY_MELEE_RANGE = "CREATURE_PROPERTIES_PRIMARY_MELEE_RANGE";