#include "CreatureProperties.hpp"

using namespace std;

CreatureProperties::CreatureProperties()
{
}

CreatureProperties::~CreatureProperties()
{
}

const string CreatureProperties::CREATURE_PROPERTIES_CHAT_SCRIPT = "CREATURE_PROPERTIES_CHAT_SCRIPT";
const string CreatureProperties::CREATURE_PROPERTIES_LAST_BESTIARY_SEARCH = "CREATURE_PROPERTIES_LAST_BESTIARY_SEARCH";
const string CreatureProperties::CREATURE_PROPERTIES_HASTE_MODIFIER = "CREATURE_PROPERTIES_HASTE_MODIFIER";
const string CreatureProperties::CREATURE_PROPERTIES_DISFIG_STR_MOD = "CREATURE_PROPERTIES_DISFIG_STR_MOD";
const string CreatureProperties::CREATURE_PROPERTIES_DISFIG_DEX_MOD = "CREATURE_PROPERTIES_DISFIG_DEX_MOD";
const string CreatureProperties::CREATURE_PROPERTIES_DISFIG_AGI_MOD = "CREATURE_PROPERTIES_DISFIG_AGI_MOD";
const string CreatureProperties::CREATURE_PROPERTIES_DISFIG_HEA_MOD = "CREATURE_PROPERTIES_DISFIG_HEA_MOD";
const string CreatureProperties::CREATURE_PROPERTIES_DISFIG_INT_MOD = "CREATURE_PROPERTIES_DISFIG_INT_MOD";
const string CreatureProperties::CREATURE_PROPERTIES_DISFIG_WIL_MOD = "CREATURE_PROPERTIES_DISFIG_WIL_MOD";
const string CreatureProperties::CREATURE_PROPERTIES_DISFIG_CHA_MOD = "CREATURE_PROPERTIES_DISFIG_CHA_MOD";

