#include "MapProperties.hpp"

using namespace std;

MapProperties::MapProperties()
{
}

MapProperties::~MapProperties()
{
}

const string MapProperties::MAP_PROPERTIES_PERMANENCE = "MAP_PROPERTIES_PERMANENCE";
const string MapProperties::MAP_PROPERTIES_GENERATED_MAP_ID = "MAP_PROPERTIES_GENERATED_MAP_ID";
const string MapProperties::MAP_PROPERTIES_WORLD_MAP_LOCATION = "MAP_PROPERTIES_WORLD_MAP_LOCATION";
const string MapProperties::MAP_PROPERTIES_WORLD_MAP_HEIGHT = "MAP_PROPERTIES_WORLD_MAP_HEIGHT";
const string MapProperties::MAP_PROPERTIES_INITIAL_CREATURES = "MAP_PROPERTIES_INITIAL_CREATURES";
const string MapProperties::MAP_PROPERTIES_INITIAL_ITEMS = "MAP_PROPERTIES_INITIAL_ITEMS";
const string MapProperties::MAP_PROPERTIES_GENERATOR_FILTERS = "MAP_PROPERTIES_GENERATOR_FILTERS";
const string MapProperties::MAP_PROPERTIES_IGNORE_CREATURE_LVL_CHECKS = "MAP_PROPERTIES_IGNORE_CREATURE_LVL_CHECKS";
const string MapProperties::MAP_PROPERTIES_CREATURE_DANGER_LEVEL_FIXED = "MAP_PROPERTIES_CREATURE_DANGER_LEVEL_FIXED";
const string MapProperties::MAP_PROPERTIES_GENERATED_CREATURE_RACE_ID = "MAP_PROPERTIES_GENERATED_CREATURE_RACE_ID";
const string MapProperties::MAP_PROPERTIES_FEATURE_ENTRY_TEXT_SIDS = "MAP_PROPERTIES_FEATURE_ENTRY_TEXT_SIDS";
const string MapProperties::MAP_PROPERTIES_CANNOT_DIG = "MAP_PROPERTIES_CANNOT_DIG";
const string MapProperties::MAP_PROPERTIES_CANNOT_TELEPORT = "MAP_PROPERTIES_CANNOT_TELEPORT";
const string MapProperties::MAP_PROPERTIES_CANNOT_PRAY = "MAP_PROPERTIES_CANNOT_PRAY";
const string MapProperties::MAP_PROPERTIES_CREATURE_GENERATION_RATE = "MAP_PROPERTIES_CREATURE_GENERATION_RATE";
const string MapProperties::MAP_PROPERTIES_PCT_CHANCE_FORAGABLES = "MAP_PROPERTIES_PCT_CHANCE_FORAGABLES";
const string MapProperties::MAP_PROPERTIES_PCT_CHANCE_HERBS = "MAP_PROPERTIES_PCT_CHANCE_HERBS";
const string MapProperties::MAP_PROPERTIES_RELIC_ID = "MAP_PROPERTIES_RELIC_ID";
const string MapProperties::MAP_PROPERTIES_CREATURE_IDS = "MAP_PROPERTIES_CREATURE_IDS";
const string MapProperties::MAP_PROPERTIES_DEPTH = "MAP_PROPERTIES_DEPTH";
const string MapProperties::MAP_PROPERTIES_MIN_DEPTH = "MAP_PROPERTIES_MIN_DEPTH";
const string MapProperties::MAP_PROPERTIES_MAX_DEPTH = "MAP_PROPERTIES_MAX_DEPTH";
const string MapProperties::MAP_PROPERTIES_SHIMMER_COLOURS = "MAP_PROPERTIES_SHIMMER_COLOURS";
const string MapProperties::MAP_PROPERTIES_GENERATION_COORDINATES = "MAP_PROPERTIES_GENERATION_COORDINATES";
const string MapProperties::MAP_PROPERTIES_EXIT_MOVEMENT_TYPE = "MAP_PROPERTIES_EXIT_MOVEMENT_TYPE";
const string MapProperties::MAP_PROPERTIES_TOMB_GUARDIANS = "MAP_PROPERTIES_TOMB_GUARDIANS";
const string MapProperties::MAP_PROPERTIES_DEFAULT_UP_STAIRCASE = "MAP_PROPERTIES_DEFAULT_UP_STAIRCASE";
const string MapProperties::MAP_PROPERTIES_DEFAULT_DOWN_STAIRCASE = "MAP_PROPERTIES_DEFAULT_DOWN_STAIRCASE";
const string MapProperties::MAP_PROPERTIES_SKIP_COASTLINE_GENERATION = "MAP_PROPERTIES_SKIP_COASTLINE_GENERATION";
const string MapProperties::MAP_PROPERTIES_COASTLINE_NORTH = "MAP_PROPERTIES_COASTLINE_NORTH";
const string MapProperties::MAP_PROPERTIES_COASTLINE_SOUTH = "MAP_PROPERTIES_COASTLINE_SOUTH";
const string MapProperties::MAP_PROPERTIES_COASTLINE_EAST = "MAP_PROPERTIES_COASTLINE_EAST";
const string MapProperties::MAP_PROPERTIES_COASTLINE_WEST = "MAP_PROPERTIES_COASTLINE_WEST";
const string MapProperties::MAP_PROPERTIES_SECONDARY_TERRAIN = "MAP_PROPERTIES_SECONDARY_TERRAIN";
const string MapProperties::MAP_PROPERTIES_DANGER_LEVEL_OVERRIDE = "MAP_PROPERTIES_DANGER_LEVEL_OVERRIDE";
const string MapProperties::MAP_PROPERTIES_VILLAGE_COORDINATES = "MAP_PROPERTIES_VILLAGE_COORDINATES";
const string MapProperties::MAP_PROPERTIES_PRESET_VILLAGE_COORDINATES = "MAP_PROPERTIES_PRESET_VILLAGE_COORDINATES";
const string MapProperties::MAP_PROPERTIES_DIVINE_FORBIDDEN = "MAP_PROPERTIES_DIVINE_FORBIDDEN";
const string MapProperties::MAP_PROPERTIES_SHALLOW_WATER = "MAP_PROPERTIES_SHALLOW_WATER";
const string MapProperties::MAP_PROPERTIES_OPEN_SKY = "MAP_PROPERTIES_OPEN_SKY";
