#pragma once

enum struct PublicSectorFeatureType
{
  PUBLIC_SECTOR_FIRST = 0,
  PUBLIC_SECTOR_FEATURE_SHOP = 0,
  PUBLIC_SECTOR_FEATURE_PLAZA = 1,
  PUBLIC_SECTOR_FEATURE_PARK = 2,
  PUBLIC_SECTOR_FEATURE_TOMB = 3,
  PUBLIC_SECTOR_FEATURE_BEER_HALL = 4,
  PUBLIC_SECTOR_FEATURE_GARDEN = 5,
  PUBLIC_SECTOR_LAST = 6
};

enum struct ReligiousCommercialSectorFeatureType
{
  RC_SECTOR_FIRST = 0,
  RC_SECTOR_FEATURE_GARDEN = 0,
  RC_SECTOR_FEATURE_ROCK_GARDEN = 1,
  RC_SECTOR_FEATURE_FLOWER_GARDEN = 2,
  RC_SECTOR_FEATURE_SHOP = 3,
  RC_SECTOR_FEATURE_OUTDOOR_SHRINE = 4,
  RC_SECTOR_FEATURE_LIBRARY = 5,
  RC_SECTOR_FEATURE_STOREHOUSE = 6,
  RC_SECTOR_LAST = 7
};

enum struct LowIncomeResidentialSectorFeatureType
{
  LIR_SECTOR_FIRST = 0,
  LIR_SECTOR_FEATURE_HOUSE = 0,
  LIR_SECTOR_FEATURE_GRAVES = 1,
  LIR_SECTOR_FEATURE_VEGETABLE_GARDEN = 2,
  LIR_SECTOR_FEATURE_ROCK_GARDEN = 3,
  LIR_SECTOR_FEATURE_SHOP = 4,
  LIR_SECTOR_FEATURE_BEER_HALL = 5,
  LIR_SECTOR_FEATURE_WORKSHOP = 6,
  LIR_SECTOR_FEATURE_TAVERN = 7,
  LIR_SECTOR_LAST = 8
};

enum struct ResidentialSectorFeatureType
{
  RESIDENTIAL_SECTOR_FIRST = 0,
  RESIDENTIAL_SECTOR_FEATURE_GRAVES = 0,
  RESIDENTIAL_SECTOR_FEATURE_ROCK_GARDEN = 1,
  RESIDENTIAL_SECTOR_FEATURE_FLOWER_GARDEN = 2,
  RESIDENTIAL_SECTOR_FEATURE_GARDEN = 3,
  RESIDENTIAL_SECTOR_FEATURE_SHOP = 4,
  RESIDENTIAL_SECTOR_FEATURE_SHRINE = 5,
  RESIDENTIAL_SECTOR_FEATURE_HOUSE = 6,
  RESIDENTIAL_SECTOR_FEATURE_WORKSHOP = 7,
  RESIDENTIAL_SECTOR_LAST = 8
};
