#pragma once

enum GainAttributesEnum
{
  GAIN_ATTRIBUTES_STRENGTH,
  GAIN_ATTRIBUTES_DEXTERITY,
  GAIN_ATTRIBUTES_AGILITY,
  GAIN_ATTRIBUTES_HEALTH,
  GAIN_ATTRIBUTES_INTELLIGENCE,
  GAIN_ATTRIBUTES_WILLPOWER,
  GAIN_ATTRIBUTES_CHARISMA
};

