#pragma once
enum struct DamageType
{
  DAMAGE_TYPE_NULL = -1,
  DAMAGE_TYPE_FIRST = 0,
  DAMAGE_TYPE_SLASH = 0,
  DAMAGE_TYPE_PIERCE = 1,
  DAMAGE_TYPE_POUND = 2,
  DAMAGE_TYPE_HEAT = 3,
  DAMAGE_TYPE_COLD = 4,
  DAMAGE_TYPE_ACID = 5,
  DAMAGE_TYPE_POISON = 6,
  DAMAGE_TYPE_HOLY = 7,
  DAMAGE_TYPE_SHADOW = 8,
  DAMAGE_TYPE_ARCANE = 9,
  DAMAGE_TYPE_LIGHTNING = 10,
  DAMAGE_TYPE_MAX = 11
};

enum struct DamageFlagType
{
  DAMAGE_FLAG_CHAOTIC = 0,
  DAMAGE_FLAG_VORPAL = 1,
  DAMAGE_FLAG_DRAINING = 2,
  DAMAGE_FLAG_ETHEREAL = 3,
  DAMAGE_FLAG_PIERCING = 4,
  DAMAGE_FLAG_INCORPOREAL = 5,
  DAMAGE_FLAG_LAST = 5
};
