#pragma once
enum struct DamageType
{
  DAMAGE_TYPE_NULL = -1,
  DAMAGE_TYPE_FIRST = 0,
  DAMAGE_TYPE_SLASH = 0,
  DAMAGE_TYPE_PIERCE = 1,
  DAMAGE_TYPE_POUND = 2,
  DAMAGE_TYPE_HEAT = 3,
  DAMAGE_TYPE_COLD = 4,
  DAMAGE_TYPE_ACID = 5,
  DAMAGE_TYPE_POISON = 6,
  DAMAGE_TYPE_HOLY = 7,
  DAMAGE_TYPE_SHADOW = 8,
  DAMAGE_TYPE_ARCANE = 9,
  DAMAGE_TYPE_LIGHTNING = 10,
  DAMAGE_TYPE_MAX = 11
};

