#pragma once
enum ResistanceType
{
  RESISTANCE_TYPE_NULL = -1,
  RESISTANCE_TYPE_SLASH = 0,
  RESISTANCE_TYPE_PIERCE = 1,
  RESISTANCE_TYPE_POUND = 2,
  RESISTANCE_TYPE_HEAT = 3,
  RESISTANCE_TYPE_COLD = 4,
  RESISTANCE_TYPE_ACID = 5,
  RESISTANCE_TYPE_POISON = 6,
  RESISTANCE_TYPE_HOLY = 7,
  RESISTANCE_TYPE_SHADOW = 8,
  RESISTANCE_TYPE_ARCANE = 9,
  RESISTANCE_TYPE_MENTAL = 10,
  RESISTANCE_TYPE_SONIC = 11,
  RESISTANCE_TYPE_RADIANT = 12,
  RESISTANCE_TYPE_LIGHTNING = 13,
  RESISTANCE_TYPE_MAX = 14
};

