#pragma once

enum struct PrimaryStatisticType
{
  PRIMARY_STATISTIC_STRENGTH = 0,
  PRIMARY_STATISTIC_DEXTERITY = 1,
  PRIMARY_STATISTIC_AGILITY = 2,
  PRIMARY_STATISTIC_HEALTH = 3,
  PRIMARY_STATISTIC_INTELLIGENCE = 4,
  PRIMARY_STATISTIC_WILLPOWER = 5,
  PRIMARY_STATISTIC_CHARISMA = 6
};
