#pragma once

enum struct WaterType
{
  WATER_TYPE_UNDEFINED,
  WATER_TYPE_FRESH,
  WATER_TYPE_SALT
};

enum struct FishingOutcomeType
{
  FISHING_OUTCOME_UNDEFINED,
  FISHING_OUTCOME_NO_CATCH,
  FISHING_OUTCOME_NIBBLE,
  FISHING_OUTCOME_ESCAPE,
  FISHING_OUTCOME_CATCH
};

