-- Update the environment to always check the "scripts" directory.
package.path = package.path .. ";./scripts/?.lua"
package.path = package.path .. ";./scripts/common/?.lua"
package.path = package.path .. ";./scripts/quests/?.lua"
package.path = package.path .. ";./scripts/quests/carcassia/?.lua"
package.path = package.path .. ";./scripts/level/?.lua"
package.path = package.path .. ";./scripts/areas/?.lua"
package.path = package.path .. ";./scripts/areas/events/?.lua"
package.path = package.path .. ";./scripts/deities/?.lua"
package.path = package.path .. ";./scripts/misc/?.lua"
package.path = package.path .. ";./scripts/attacks/?.lua"
package.path = package.path .. ";./scripts/decision/?.lua"
package.path = package.path .. ";./scripts/drop/?.lua"
package.path = package.path .. ";./scripts/items/?.lua"
package.path = package.path .. ";./scripts/death/?.lua"
package.path = package.path .. ";./scripts/kill/?.lua"
