#pragma once

enum struct RoomType
{
  ROOM_TYPE_BASIC = 0,
  ROOM_TYPE_SPECIAL_FIRST = 1,
  ROOM_TYPE_X = 1,
  ROOM_TYPE_WET = 2,
  ROOM_TYPE_DANK = 3,
  ROOM_TYPE_CAVE_IN = 4,
  ROOM_TYPE_MUSH_ROOM = 5,
  ROOM_TYPE_SPECIAL_LAST_INC = 5,
  ROOM_TYPE_LAST = 6
};

