#pragma once

enum struct CitySectorType
{
  CITY_SECTOR_NULL = 0,
  CITY_SECTOR_PUBLIC_AREA = 1,
  CITY_SECTOR_LOW_INCOME_RESIDENTIAL = 2,
  CITY_SECTOR_RESIDENTIAL = 3,
  CITY_SECTOR_RELIGIOUS_COMMERCIAL = 4
};

#define CCITY_SECTOR_PUBLIC_AREA 1
#define CCITY_SECTOR_LOW_INCOME_RESIDENTIAL 2
#define CCITY_SECTOR_RESIDENTIAL 3
#define CCITY_SECTOR_RELIGIOUS_COMMERCIAL 4

