#pragma once

enum ClassIdentifier
{
  CLASS_ID_NULL = 0,
  CLASS_ID_GAME,
  CLASS_ID_CURSES_DISPLAY,
  CLASS_ID_COMMAND_FACTORY,
  CLASS_ID_EQUIPMENT_COMMAND_FACTORY,
  CLASS_ID_INVENTORY_COMMAND_FACTORY,
  CLASS_ID_TILE_SELECTION_COMMAND_FACTORY
};
