#include "gtest/gtest.h"

TEST(SW_Engine_Scripting_SciptEngine, lua_constants_match_enum_values_log)
{
  EXPECT_TRUE(LoggingLevel(CLOG_DEBUG) == LoggingLevel::LOG_DEBUG);
  EXPECT_TRUE(LoggingLevel(CLOG_ERROR)== LoggingLevel::LOG_ERROR);
  EXPECT_TRUE(LoggingLevel(CLOG_INFO) == LoggingLevel::LOG_INFO);
  EXPECT_TRUE(LoggingLevel(CLOG_TRACE) == LoggingLevel::LOG_TRACE);
}

TEST(SW_Engine_Scripting_SciptEngine, lua_constants_match_enum_values_direction)
{
  EXPECT_TRUE(Direction(CDIRECTION_SOUTH) == Direction::DIRECTION_SOUTH);
  EXPECT_TRUE(Direction(CDIRECTION_SOUTH_WEST) == Direction::DIRECTION_SOUTH_WEST);
  EXPECT_TRUE(Direction(CDIRECTION_SOUTH_EAST) == Direction::DIRECTION_SOUTH_EAST);
  EXPECT_TRUE(Direction(CDIRECTION_WEST) == Direction::DIRECTION_WEST);
  EXPECT_TRUE(Direction(CDIRECTION_NULL) == Direction::DIRECTION_NULL);
  EXPECT_TRUE(Direction(CDIRECTION_EAST) == Direction::DIRECTION_EAST);
  EXPECT_TRUE(Direction(CDIRECTION_NORTH_WEST) == Direction::DIRECTION_NORTH_WEST);
  EXPECT_TRUE(Direction(CDIRECTION_NORTH_EAST) == Direction::DIRECTION_NORTH_EAST);
  EXPECT_TRUE(Direction(CDIRECTION_NORTH) == Direction::DIRECTION_NORTH);
  EXPECT_TRUE(Direction(CDIRECTION_UP) == Direction::DIRECTION_UP);
  EXPECT_TRUE(Direction(CDIRECTION_DOWN) == Direction::DIRECTION_DOWN);
}

TEST(SW_Engine_Scripting_SciptEngine, lua_constants_match_enum_values_item_type)
{
  EXPECT_TRUE(ItemType(CITEM_TYPE_AMULET) == ItemType::ITEM_TYPE_AMULET);
  EXPECT_TRUE(ItemType(CITEM_TYPE_POTION) == ItemType::ITEM_TYPE_POTION);
  EXPECT_TRUE(ItemType(CITEM_TYPE_RING) == ItemType::ITEM_TYPE_RING);
  EXPECT_TRUE(ItemType(CITEM_TYPE_SCROLL) == ItemType::ITEM_TYPE_SCROLL);
  EXPECT_TRUE(ItemType(CITEM_TYPE_SPELLBOOK) == ItemType::ITEM_TYPE_SPELLBOOK);
  EXPECT_TRUE(ItemType(CITEM_TYPE_WAND) == ItemType::ITEM_TYPE_WAND);
}

// Item filter is used only for Idem, and doesn't have an equivalent within
// the engine.

TEST(SW_Engine_Scripting_SciptEngine, lua_constants_match_enum_values_skills)
{
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_ARCHERY) == SkillType::SKILL_GENERAL_ARCHERY);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_AWARENESS) == SkillType::SKILL_GENERAL_AWARENESS);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_BARGAINING) == SkillType::SKILL_GENERAL_BARGAINING);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_BEASTMASTERY) == SkillType::SKILL_GENERAL_BEASTMASTERY);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_BLIND_FIGHTING) == SkillType::SKILL_GENERAL_BLIND_FIGHTING);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_BOATING) == SkillType::SKILL_GENERAL_BOATING);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_BOWYER) == SkillType::SKILL_GENERAL_BOWYER);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_BREWING) == SkillType::SKILL_GENERAL_BREWING);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_CARRYING) == SkillType::SKILL_GENERAL_CARRYING);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_COMBAT) == SkillType::SKILL_GENERAL_COMBAT);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_CRAFTING) == SkillType::SKILL_GENERAL_CRAFTING);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_DESERT_LORE) == SkillType::SKILL_GENERAL_DESERT_LORE);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_DETECTION) == SkillType::SKILL_GENERAL_DETECTION);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_DISARM_TRAPS) == SkillType::SKILL_GENERAL_DISARM_TRAPS);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_DUAL_WIELD) == SkillType::SKILL_GENERAL_DUAL_WIELD);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_DUNGEONEERING) == SkillType::SKILL_GENERAL_DUNGEONEERING);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_ESCAPE) == SkillType::SKILL_GENERAL_ESCAPE);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_FISHING) == SkillType::SKILL_GENERAL_FISHING);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_FLETCHERY) == SkillType::SKILL_GENERAL_FLETCHERY);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_FORAGING) == SkillType::SKILL_GENERAL_FORAGING);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_FOREST_LORE) == SkillType::SKILL_GENERAL_FOREST_LORE);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_HERBALISM) == SkillType::SKILL_GENERAL_HERBALISM);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_HIDING) == SkillType::SKILL_GENERAL_HIDING);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_HUNTING) == SkillType::SKILL_GENERAL_HUNTING);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_INTIMIDATION) == SkillType::SKILL_GENERAL_INTIMIDATION);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_JEWELER) == SkillType::SKILL_GENERAL_JEWELER);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_JUMPING) == SkillType::SKILL_GENERAL_JUMPING);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_LEADERSHIP) == SkillType::SKILL_GENERAL_LEADERSHIP);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_LITERACY) == SkillType::SKILL_GENERAL_LITERACY);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_LORE) == SkillType::SKILL_GENERAL_LORE);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_MAGIC) == SkillType::SKILL_GENERAL_MAGIC);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_MARSH_LORE) == SkillType::SKILL_GENERAL_MARSH_LORE);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_MEDICINE) == SkillType::SKILL_GENERAL_MEDICINE);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_MOUNTAIN_LORE) == SkillType::SKILL_GENERAL_MOUNTAIN_LORE);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_MUSIC) == SkillType::SKILL_GENERAL_MUSIC);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_NIGHT_SIGHT) == SkillType::SKILL_GENERAL_NIGHT_SIGHT);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_OCEAN_LORE) == SkillType::SKILL_GENERAL_OCEAN_LORE);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_PAPERCRAFT) == SkillType::SKILL_GENERAL_PAPERCRAFT);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_RELIGION) == SkillType::SKILL_GENERAL_RELIGION);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_SCRIBING) == SkillType::SKILL_GENERAL_SCRIBING);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_SKINNING) == SkillType::SKILL_GENERAL_SKINNING);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_SMITHING) == SkillType::SKILL_GENERAL_SMITHING);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_SPELUNKING) == SkillType::SKILL_GENERAL_SPELUNKING);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_STEALTH) == SkillType::SKILL_GENERAL_STEALTH);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_SWIMMING) == SkillType::SKILL_GENERAL_SWIMMING);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_TANNING) == SkillType::SKILL_GENERAL_TANNING);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_THIEVERY) == SkillType::SKILL_GENERAL_THIEVERY);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_WANDCRAFT) == SkillType::SKILL_GENERAL_WANDCRAFT);
  EXPECT_TRUE(SkillType(CSKILL_GENERAL_WEAVING) == SkillType::SKILL_GENERAL_WEAVING);

  EXPECT_TRUE(SkillType(CSKILL_MELEE_AXES) == SkillType::SKILL_MELEE_AXES);
  EXPECT_TRUE(SkillType(CSKILL_MELEE_BLUDGEONS) == SkillType::SKILL_MELEE_BLUDGEONS);
  EXPECT_TRUE(SkillType(CSKILL_MELEE_DAGGERS) == SkillType::SKILL_MELEE_DAGGERS);
  EXPECT_TRUE(SkillType(CSKILL_MELEE_EXOTIC) == SkillType::SKILL_MELEE_EXOTIC);
  EXPECT_TRUE(SkillType(CSKILL_MELEE_LONG_BLADES) == SkillType::SKILL_MELEE_LONG_BLADES);
  EXPECT_TRUE(SkillType(CSKILL_MELEE_RODS_AND_STAVES) == SkillType::SKILL_MELEE_RODS_AND_STAVES);
  EXPECT_TRUE(SkillType(CSKILL_MELEE_SHORT_BLADES) == SkillType::SKILL_MELEE_SHORT_BLADES);
  EXPECT_TRUE(SkillType(CSKILL_MELEE_SPEARS) == SkillType::SKILL_MELEE_SPEARS);
  EXPECT_TRUE(SkillType(CSKILL_MELEE_UNARMED) == SkillType::SKILL_MELEE_UNARMED);
  EXPECT_TRUE(SkillType(CSKILL_MELEE_WHIPS) == SkillType::SKILL_MELEE_WHIPS);

  EXPECT_TRUE(SkillType(CSKILL_RANGED_AXES) == SkillType::SKILL_RANGED_AXES);
  EXPECT_TRUE(SkillType(CSKILL_RANGED_BLADES) == SkillType::SKILL_RANGED_BLADES);
  EXPECT_TRUE(SkillType(CSKILL_RANGED_BLUDGEONS) == SkillType::SKILL_RANGED_BLUDGEONS);
  EXPECT_TRUE(SkillType(CSKILL_RANGED_BOWS) == SkillType::SKILL_RANGED_BOWS);
  EXPECT_TRUE(SkillType(CSKILL_RANGED_CROSSBOWS) == SkillType::SKILL_RANGED_CROSSBOWS);
  EXPECT_TRUE(SkillType(CSKILL_RANGED_DAGGERS) == SkillType::SKILL_RANGED_DAGGERS);
  EXPECT_TRUE(SkillType(CSKILL_RANGED_EXOTIC) == SkillType::SKILL_RANGED_EXOTIC);
  EXPECT_TRUE(SkillType(CSKILL_RANGED_ROCKS) == SkillType::SKILL_RANGED_ROCKS);
  EXPECT_TRUE(SkillType(CSKILL_RANGED_SLINGS) == SkillType::SKILL_RANGED_SLINGS);
  EXPECT_TRUE(SkillType(CSKILL_RANGED_SPEARS) == SkillType::SKILL_RANGED_SPEARS);

  EXPECT_TRUE(SkillType(CSKILL_MAGIC_ARCANE) == SkillType::SKILL_MAGIC_ARCANE);
  EXPECT_TRUE(SkillType(CSKILL_MAGIC_CANTRIPS) == SkillType::SKILL_MAGIC_CANTRIPS);
  EXPECT_TRUE(SkillType(CSKILL_MAGIC_DIVINE) == SkillType::SKILL_MAGIC_DIVINE);
  EXPECT_TRUE(SkillType(CSKILL_MAGIC_MYSTIC) == SkillType::SKILL_MAGIC_MYSTIC);
  EXPECT_TRUE(SkillType(CSKILL_MAGIC_PRIMORDIAL) == SkillType::SKILL_MAGIC_PRIMORDIAL);
}

TEST(SW_Engine_Scripting_ScriptEngine, serialization_id)
{
  ScriptEngine se;

  EXPECT_EQ(ClassIdentifier::CLASS_ID_SCRIPT_ENGINE, se.get_class_identifier());
}

TEST(SW_engine_Scripting_ScriptEngine, saveload)
{
  ScriptEngine se, se2;

  se.set_last_executed("some_lua_command");

  ostringstream ss;

  se.serialize(ss);

  istringstream iss(ss.str());

  se2.deserialize(iss);

  EXPECT_TRUE(se == se2);
}

